name: Test & build (Multi job)

on:
  push:
    branches:
      - mb
  pull_request:
    branches:
      - mb

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Node.js application

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint
      - name: Run Lint
        run: npm run lint

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    name: Build & Push Docker image
    needs: test  # This ensures the build job only runs if the test job passes

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-node-app:${{ github.sha }} .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-node-app:${{ github.sha }}

      # Optional: Tag the Docker image with `latest`
      - name: Tag Docker image with 'latest'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/cicd-node-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/cicd-node-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-node-app:latest
